name: jest dynamic test

on:
  push:
jobs:
  run-jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm i
      - name: Run test
        run: npm run test
